name: connex
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.11
  - numpy
  - scipy  
  - pandas
  - xarray
  - netCDF4
  - matplotlib
  - geopandas
  - shapely
  - pyproj
  - fiona
  - parcels
  - gdal
  - pip
  - pip:
      - wget

